// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: backendLobby.proto

package backendLobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarEnum int32

const (
	AvatarEnum_ZERO AvatarEnum = 0
	AvatarEnum_ONE  AvatarEnum = 1
)

// Enum value maps for AvatarEnum.
var (
	AvatarEnum_name = map[int32]string{
		0: "ZERO",
		1: "ONE",
	}
	AvatarEnum_value = map[string]int32{
		"ZERO": 0,
		"ONE":  1,
	}
)

func (x AvatarEnum) Enum() *AvatarEnum {
	p := new(AvatarEnum)
	*p = x
	return p
}

func (x AvatarEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvatarEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_backendLobby_proto_enumTypes[0].Descriptor()
}

func (AvatarEnum) Type() protoreflect.EnumType {
	return &file_backendLobby_proto_enumTypes[0]
}

func (x AvatarEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvatarEnum.Descriptor instead.
func (AvatarEnum) EnumDescriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{0}
}

type GenderEnum int32

const (
	GenderEnum_GIRL GenderEnum = 0
	GenderEnum_BOY  GenderEnum = 1
)

// Enum value maps for GenderEnum.
var (
	GenderEnum_name = map[int32]string{
		0: "GIRL",
		1: "BOY",
	}
	GenderEnum_value = map[string]int32{
		"GIRL": 0,
		"BOY":  1,
	}
)

func (x GenderEnum) Enum() *GenderEnum {
	p := new(GenderEnum)
	*p = x
	return p
}

func (x GenderEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenderEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_backendLobby_proto_enumTypes[1].Descriptor()
}

func (GenderEnum) Type() protoreflect.EnumType {
	return &file_backendLobby_proto_enumTypes[1]
}

func (x GenderEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenderEnum.Descriptor instead.
func (GenderEnum) EnumDescriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{1}
}

type EmptyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{0}
}

// GetMemberList
type GetMemberListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int64           `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Message    string          `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data       *MemberListInfo `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetMemberListRes) Reset() {
	*x = GetMemberListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberListRes) ProtoMessage() {}

func (x *GetMemberListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberListRes.ProtoReflect.Descriptor instead.
func (*GetMemberListRes) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{1}
}

func (x *GetMemberListRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetMemberListRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMemberListRes) GetData() *MemberListInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type MemberListInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberList []*MemberList `protobuf:"bytes,1,rep,name=memberList,proto3" json:"memberList,omitempty"`
}

func (x *MemberListInfo) Reset() {
	*x = MemberListInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListInfo) ProtoMessage() {}

func (x *MemberListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListInfo.ProtoReflect.Descriptor instead.
func (*MemberListInfo) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{2}
}

func (x *MemberListInfo) GetMemberList() []*MemberList {
	if x != nil {
		return x.MemberList
	}
	return nil
}

type MemberList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        string     `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password       string     `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Avatar         AvatarEnum `protobuf:"varint,3,opt,name=avatar,proto3,enum=backendLobby.AvatarEnum" json:"avatar,omitempty"`
	Gender         GenderEnum `protobuf:"varint,4,opt,name=gender,proto3,enum=backendLobby.GenderEnum" json:"gender,omitempty"`
	LastLoginTime  int64      `protobuf:"varint,5,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	LastLogoutTime int64      `protobuf:"varint,6,opt,name=lastLogoutTime,proto3" json:"lastLogoutTime,omitempty"`
	Balance        int64      `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{3}
}

func (x *MemberList) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MemberList) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MemberList) GetAvatar() AvatarEnum {
	if x != nil {
		return x.Avatar
	}
	return AvatarEnum_ZERO
}

func (x *MemberList) GetGender() GenderEnum {
	if x != nil {
		return x.Gender
	}
	return GenderEnum_GIRL
}

func (x *MemberList) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *MemberList) GetLastLogoutTime() int64 {
	if x != nil {
		return x.LastLogoutTime
	}
	return 0
}

func (x *MemberList) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// SetMember
type SetMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string     `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password string     `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Gender   AvatarEnum `protobuf:"varint,3,opt,name=Gender,proto3,enum=backendLobby.AvatarEnum" json:"Gender,omitempty"`
	Avatar   GenderEnum `protobuf:"varint,4,opt,name=Avatar,proto3,enum=backendLobby.GenderEnum" json:"Avatar,omitempty"`
	Balance  int64      `protobuf:"varint,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
}

func (x *SetMember) Reset() {
	*x = SetMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMember) ProtoMessage() {}

func (x *SetMember) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMember.ProtoReflect.Descriptor instead.
func (*SetMember) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{4}
}

func (x *SetMember) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SetMember) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetMember) GetGender() AvatarEnum {
	if x != nil {
		return x.Gender
	}
	return AvatarEnum_ZERO
}

func (x *SetMember) GetAvatar() GenderEnum {
	if x != nil {
		return x.Avatar
	}
	return GenderEnum_GIRL
}

func (x *SetMember) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type SetMemberRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int64  `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *SetMemberRes) Reset() {
	*x = SetMemberRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMemberRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRes) ProtoMessage() {}

func (x *SetMemberRes) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRes.ProtoReflect.Descriptor instead.
func (*SetMemberRes) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{5}
}

func (x *SetMemberRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SetMemberRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetGameList
type GetGameListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int64               `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Message    string              `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data       *GetGameListResInfo `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetGameListRes) Reset() {
	*x = GetGameListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListRes) ProtoMessage() {}

func (x *GetGameListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListRes.ProtoReflect.Descriptor instead.
func (*GetGameListRes) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{6}
}

func (x *GetGameListRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetGameListRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGameListRes) GetData() *GetGameListResInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGameListResInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameList []*GameList `protobuf:"bytes,1,rep,name=gameList,proto3" json:"gameList,omitempty"`
}

func (x *GetGameListResInfo) Reset() {
	*x = GetGameListResInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListResInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListResInfo) ProtoMessage() {}

func (x *GetGameListResInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListResInfo.ProtoReflect.Descriptor instead.
func (*GetGameListResInfo) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameListResInfo) GetGameList() []*GameList {
	if x != nil {
		return x.GameList
	}
	return nil
}

type GameList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int64 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Status bool  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *GameList) Reset() {
	*x = GameList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameList) ProtoMessage() {}

func (x *GameList) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameList.ProtoReflect.Descriptor instead.
func (*GameList) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{8}
}

func (x *GameList) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameList) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// SetGame
type SetGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int64 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	Status bool  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *SetGame) Reset() {
	*x = SetGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGame) ProtoMessage() {}

func (x *SetGame) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGame.ProtoReflect.Descriptor instead.
func (*SetGame) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{9}
}

func (x *SetGame) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SetGame) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// KickOutMember
type KickOutMemberInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Balance int64  `protobuf:"varint,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
}

func (x *KickOutMemberInfo) Reset() {
	*x = KickOutMemberInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickOutMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOutMemberInfo) ProtoMessage() {}

func (x *KickOutMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOutMemberInfo.ProtoReflect.Descriptor instead.
func (*KickOutMemberInfo) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{10}
}

func (x *KickOutMemberInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *KickOutMemberInfo) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type KickOutMemberRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int64  `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *KickOutMemberRes) Reset() {
	*x = KickOutMemberRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickOutMemberRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOutMemberRes) ProtoMessage() {}

func (x *KickOutMemberRes) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOutMemberRes.ProtoReflect.Descriptor instead.
func (*KickOutMemberRes) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{11}
}

func (x *KickOutMemberRes) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *KickOutMemberRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateMemberData
type UpdateMemberData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        string     `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password       string     `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Avatar         AvatarEnum `protobuf:"varint,3,opt,name=Avatar,proto3,enum=backendLobby.AvatarEnum" json:"Avatar,omitempty"`
	Gender         GenderEnum `protobuf:"varint,4,opt,name=Gender,proto3,enum=backendLobby.GenderEnum" json:"Gender,omitempty"`
	IsAdmin        bool       `protobuf:"varint,5,opt,name=IsAdmin,proto3" json:"IsAdmin,omitempty"`
	Balance        int64      `protobuf:"varint,6,opt,name=Balance,proto3" json:"Balance,omitempty"`
	LastLoginTime  int64      `protobuf:"varint,7,opt,name=LastLoginTime,proto3" json:"LastLoginTime,omitempty"`
	LastLogoutTime int64      `protobuf:"varint,8,opt,name=LastLogoutTime,proto3" json:"LastLogoutTime,omitempty"`
}

func (x *UpdateMemberData) Reset() {
	*x = UpdateMemberData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMemberData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberData) ProtoMessage() {}

func (x *UpdateMemberData) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberData.ProtoReflect.Descriptor instead.
func (*UpdateMemberData) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMemberData) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UpdateMemberData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateMemberData) GetAvatar() AvatarEnum {
	if x != nil {
		return x.Avatar
	}
	return AvatarEnum_ZERO
}

func (x *UpdateMemberData) GetGender() GenderEnum {
	if x != nil {
		return x.Gender
	}
	return GenderEnum_GIRL
}

func (x *UpdateMemberData) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UpdateMemberData) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UpdateMemberData) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *UpdateMemberData) GetLastLogoutTime() int64 {
	if x != nil {
		return x.LastLogoutTime
	}
	return 0
}

// UpdateGameList
type UpdateGameList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameList []*GameList `protobuf:"bytes,1,rep,name=gameList,proto3" json:"gameList,omitempty"`
}

func (x *UpdateGameList) Reset() {
	*x = UpdateGameList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backendLobby_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameList) ProtoMessage() {}

func (x *UpdateGameList) ProtoReflect() protoreflect.Message {
	mi := &file_backendLobby_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameList.ProtoReflect.Descriptor instead.
func (*UpdateGameList) Descriptor() ([]byte, []int) {
	return file_backendLobby_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateGameList) GetGameList() []*GameList {
	if x != nil {
		return x.GameList
	}
	return nil
}

var File_backendLobby_proto protoreflect.FileDescriptor

var file_backendLobby_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x22, 0x7e,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4a,
	0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x38, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0a,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x8e, 0x02, 0x0a, 0x0a, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x30, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x30, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61, 0x73,
	0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x09,
	0x53, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x30, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x30, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x48, 0x0a,
	0x0c, 0x53, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x32, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x39, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x4b,
	0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x22, 0x4c, 0x0a, 0x10, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0xae, 0x02, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x30, 0x0a,
	0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x30, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x47,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x4c, 0x61,
	0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4c,
	0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0e, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x1f, 0x0a, 0x0a, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x5a, 0x45, 0x52, 0x4f, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x2a, 0x1f, 0x0a, 0x0a, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x49, 0x52, 0x4c,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x4f, 0x59, 0x10, 0x01, 0x32, 0xe8, 0x01, 0x0a, 0x05,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x47, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1e,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x44,
	0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x17, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x53,
	0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x0d, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x1e, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backendLobby_proto_rawDescOnce sync.Once
	file_backendLobby_proto_rawDescData = file_backendLobby_proto_rawDesc
)

func file_backendLobby_proto_rawDescGZIP() []byte {
	file_backendLobby_proto_rawDescOnce.Do(func() {
		file_backendLobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_backendLobby_proto_rawDescData)
	})
	return file_backendLobby_proto_rawDescData
}

var file_backendLobby_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_backendLobby_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_backendLobby_proto_goTypes = []interface{}{
	(AvatarEnum)(0),            // 0: backendLobby.AvatarEnum
	(GenderEnum)(0),            // 1: backendLobby.GenderEnum
	(*EmptyReq)(nil),           // 2: backendLobby.EmptyReq
	(*GetMemberListRes)(nil),   // 3: backendLobby.GetMemberListRes
	(*MemberListInfo)(nil),     // 4: backendLobby.MemberListInfo
	(*MemberList)(nil),         // 5: backendLobby.MemberList
	(*SetMember)(nil),          // 6: backendLobby.SetMember
	(*SetMemberRes)(nil),       // 7: backendLobby.SetMemberRes
	(*GetGameListRes)(nil),     // 8: backendLobby.GetGameListRes
	(*GetGameListResInfo)(nil), // 9: backendLobby.GetGameListResInfo
	(*GameList)(nil),           // 10: backendLobby.GameList
	(*SetGame)(nil),            // 11: backendLobby.SetGame
	(*KickOutMemberInfo)(nil),  // 12: backendLobby.KickOutMemberInfo
	(*KickOutMemberRes)(nil),   // 13: backendLobby.KickOutMemberRes
	(*UpdateMemberData)(nil),   // 14: backendLobby.UpdateMemberData
	(*UpdateGameList)(nil),     // 15: backendLobby.UpdateGameList
}
var file_backendLobby_proto_depIdxs = []int32{
	4,  // 0: backendLobby.GetMemberListRes.Data:type_name -> backendLobby.MemberListInfo
	5,  // 1: backendLobby.MemberListInfo.memberList:type_name -> backendLobby.MemberList
	0,  // 2: backendLobby.MemberList.avatar:type_name -> backendLobby.AvatarEnum
	1,  // 3: backendLobby.MemberList.gender:type_name -> backendLobby.GenderEnum
	0,  // 4: backendLobby.SetMember.Gender:type_name -> backendLobby.AvatarEnum
	1,  // 5: backendLobby.SetMember.Avatar:type_name -> backendLobby.GenderEnum
	9,  // 6: backendLobby.GetGameListRes.Data:type_name -> backendLobby.GetGameListResInfo
	10, // 7: backendLobby.GetGameListResInfo.gameList:type_name -> backendLobby.GameList
	0,  // 8: backendLobby.UpdateMemberData.Avatar:type_name -> backendLobby.AvatarEnum
	1,  // 9: backendLobby.UpdateMemberData.Gender:type_name -> backendLobby.GenderEnum
	10, // 10: backendLobby.UpdateGameList.gameList:type_name -> backendLobby.GameList
	2,  // 11: backendLobby.Lobby.GetMemberList:input_type -> backendLobby.EmptyReq
	6,  // 12: backendLobby.Lobby.SetMemberData:input_type -> backendLobby.SetMember
	12, // 13: backendLobby.Lobby.KickOutMember:input_type -> backendLobby.KickOutMemberInfo
	3,  // 14: backendLobby.Lobby.GetMemberList:output_type -> backendLobby.GetMemberListRes
	7,  // 15: backendLobby.Lobby.SetMemberData:output_type -> backendLobby.SetMemberRes
	13, // 16: backendLobby.Lobby.KickOutMember:output_type -> backendLobby.KickOutMemberRes
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_backendLobby_proto_init() }
func file_backendLobby_proto_init() {
	if File_backendLobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backendLobby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberListInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMemberRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListResInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickOutMemberInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickOutMemberRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMemberData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backendLobby_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backendLobby_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backendLobby_proto_goTypes,
		DependencyIndexes: file_backendLobby_proto_depIdxs,
		EnumInfos:         file_backendLobby_proto_enumTypes,
		MessageInfos:      file_backendLobby_proto_msgTypes,
	}.Build()
	File_backendLobby_proto = out.File
	file_backendLobby_proto_rawDesc = nil
	file_backendLobby_proto_goTypes = nil
	file_backendLobby_proto_depIdxs = nil
}
